import Head from 'next/head'
import { Inter } from 'next/font/google'
import AboutMe from '@/components/AboutMe/AboutMe'
import TechStack from '@/components/TechStack/techStack'
import WorkExperience from '@/components/Experience/Experience'
import Projects from '@/components/Projects/Projects'
import Footer from '@/components/Footer/Footer'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <div>
      <Head>
        <title>Sharma Ji - Frontend Developer</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='wrapper'>
        <AboutMe />
        <TechStack />
        <WorkExperience />
        <Projects />
        <Footer />
      </div>
    </div>
  )
}
